# corewake — generates <build>/aliases/aliases.INI
# Use: cmake -DENV=<.env> -DGENERIC=<generic> -DOUT=<out> -P

if(NOT DEFINED ENV OR NOT DEFINED GENERIC OR NOT DEFINED OUT)
    message(FATAL_ERROR "generate_aliases.cmake: missing ENV, GENERIC or OUT")
endif()
get_filename_component(_d "${OUT}" DIRECTORY)
get_filename_component(_out_name "${OUT}" NAME)
file(MAKE_DIRECTORY "${_d}")
if(EXISTS "${ENV}")
    file(COPY "${ENV}" DESTINATION "${_d}")
    get_filename_component(_src_name "${ENV}" NAME)
    if(NOT _src_name STREQUAL _out_name)
        file(RENAME "${_d}/${_src_name}" "${_d}/${_out_name}")
    endif()
    message(STATUS "[corewake] aliases.INI <- .env")
else()
    file(COPY "${GENERIC}" DESTINATION "${_d}")
    get_filename_component(_src_name "${GENERIC}" NAME)
    if(NOT _src_name STREQUAL _out_name)
        file(RENAME "${_d}/${_src_name}" "${_d}/${_out_name}")
    endif()
    message(STATUS "[corewake] no .env -> aliases.INI generic")
endif()